### ISSUE TITLE
Remove a scheduler without destroying the cloud function and other schedulers

### ISSUE THREAD

**Issue by amirbtb** [anovis/goblet#120]
Hello,
I have a function decorated with multiples `@app.schedule()`, thanks to #92. 
Now I need to remove one of the schedulers without destroying the function and the other schedulers.
I tried to remove it and redeploy, it removes the unwanted schedule but redeploys the remaining ones, creating duplicates.
Is there a way to solve this issue without destroying all the resources ?
Thanks !

**Comment by anovis** [comment]
That's a good point. Typically this is solved via a state file, but i would like to avoid having all of that overhead and management and focus on making goblet more declarative. The easiest option would be to manually delete outdated functions/ resources, and can build in some cli commands into goblet for that. 
However, I think a better option would be to create a `sync` command that would look at all resources and see which ones are outdated since we use specific naming conventions for deploying various resources.

**Comment by amirbtb** [comment]
I totally agree for the `sync` command, that would be very useful in a CI pipeline, right after the `deploy` command.

**Comment by amirbtb** [comment]
I'm not sure of the correct order, would you recommend to run `sync` first then `deploy` or the other way around ?

**Comment by anovis** [comment]
I would recommend the deploy first, and the sync afterwards to clean up any resources not needed anymore. i would try in dryrun mode the first few times to make sure you are not deleting anything you are not expecting since it is based on goblet naming to detect resources not needed anymore.
