### ISSUE TITLE
Add optional argument to keep last version of archive + delete archive in Cloud Storage when deleting the function

### ISSUE THREAD

**Issue by amirbtb** [anovis/goblet#98]
Hello,

I noticed that the bucket used to store Cloud Function archives contains all the versions of all cloud functions deployed in the project. The number of objets is quite big after a couple of dev/try/test deployments. 

Feature request :
- add an optional argument to `goblet deploy` to delete the previous version of the archive in Cloud Storage
- add an optional argument to `goblet destroy` to delete the archive of the function in Cloud Storage

Thanks !

**Comment by anovis** [comment]
thats a great idea. I did look into it before in the past, but gcp doesn't have too much documented on best practices. 
The problem is behind the scenes they are using docker containers, so all previous versions often share layers with the latest. So if you delete old layers, the current function may not work properly. In that case the best option would be to remove all files for that cloudfuncion and then redploy from sratch. 

So that is certainly one option I can look into. 

The other option is to add LIfe cycle rules to the buckets so that old/ unsed buckets are removed overtime if they are not used or updated, but i think that option should be configured by the user. 

the best documentation from gcp I found was referring to[ firebase cloudfunctions](https://firebase.google.com/docs/functions?hl=en#lifecycle_of_a_background_function) which state 

```
When you update the function by deploying updated code, instances for older versions are cleaned up along with build artifacts in Cloud Storage and Container Registry, and replaced by new instances.
When you delete the function, all instances and zip archives are cleaned up, along with related build artifacts in Cloud Storage and Container Registry. The connection between the function and the event provider is removed.
```

however, I am not sure if this is currently the same for normal cloudfunctions as well

**Comment by anovis** [comment]
I did find this [article](https://krasimirtsonev.com/blog/article/firebase-gcp-saving-money), which makes me it might be possible to look at the tags and remove older ones

**Comment by amirbtb** [comment]
Ok so according to the article you found, the mechanism would work based on the tag **latest** and delete all versions that doesn't have this tag ; I believe it's a correct process. 
Are you going to add a dedicated command or add an argument to `goblet deploy` & `goblet destroy` ?

**Comment by anovis** [comment]
yup. will work on adding this funtionality. i think i will have `goblet-destroy` have a flag to remove all images as well. 
and maybe a new cli action `goblet storage optimize` or something that removes all images except `latest`

**Comment by anovis** [comment]
after doing some research it looks like gcp already removed outdated versions and keeps only the latest two. 

since that is the case i will just add a param --all to `goblet destroy --all` which will remove the artifacts when destroying a cloudfunction

**Comment by anovis** [comment]
after doing some research it looks like gcp already removed outdated versions and keeps only the latest two. 

since that is the case i will just add a param --all to `goblet destroy --all` which will remove the artifacts when destroying a cloudfunction

**Comment by amirbtb** [comment]
That's exactly what I needed. Thank you again !

**Comment by amirbtb** [comment]
I just tried the `goblet destroy --all` command and I got the following error
```
Traceback (most recent call last):
  File "/src/goblet_venv/bin/goblet", line 8, in <module>
    sys.exit(main())
  File "/src/goblet_venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/src/goblet_venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/src/goblet_venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/src/goblet_venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/src/goblet_venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/src/goblet_venv/lib/python3.8/site-packages/goblet/cli.py", line 85, in destroy
    Deployer({"name": app.function_name}).destroy(app, all)
  File "/src/goblet_venv/lib/python3.8/site-packages/goblet/deploy.py", line 68, in destroy
    destroy_cloudfunction_artifacts(self.name)
  File "/src/goblet_venv/lib/python3.8/site-packages/goblet/deploy.py", line 206, in destroy_cloudfunction_artifacts
    resp = http.request(f"https://storage.googleapis.com/storage/v1/b/{bucket_name}/o?prefix={name}")
  File "/src/goblet_venv/lib/python3.8/site-packages/google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
  File "/src/goblet_venv/lib/python3.8/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/src/goblet_venv/lib/python3.8/site-packages/google/oauth2/service_account.py", line 408, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "/src/goblet_venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 193, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/src/goblet_venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 165, in _token_endpoint_request
    _handle_error_response(response_data)
  File "/src/goblet_venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_scope: Invalid OAuth scope or ID token audience provided.', {'error': 'invalid_scope', 'error_description': 'Invalid OAuth scope or ID token audience provided.'})
```
Neither the function nor the deployment package are deleted.

**Comment by anovis** [comment]
hmm that looks like an auth error. do you mind trying to run `gcloud auth application-default login` before running the command. 

and the function should still have been deleted since that occurs before the artifacts are destroyed. 

the artifact destrpy worked for me, but this endpoint was using a different way to auth since the generic api is a different format for some reason. 

I also use conda so it could be a venv issues.
